// Code generated by MockGen. DO NOT EDIT.
// Source: model/event/event.go
//
// Generated by this command:
//
//	mockgen -source=model/event/event.go -destination=mocks/event_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	event "murl/internal/model/event"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockEvent) GetID() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockEventMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockEvent)(nil).GetID))
}

// GetParents mocks base method.
func (m *MockEvent) GetParents() []uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParents")
	ret0, _ := ret[0].([]uuid.UUID)
	return ret0
}

// GetParents indicates an expected call of GetParents.
func (mr *MockEventMockRecorder) GetParents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParents", reflect.TypeOf((*MockEvent)(nil).GetParents))
}

// GetPayload mocks base method.
func (m *MockEvent) GetPayload(dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockEventMockRecorder) GetPayload(dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockEvent)(nil).GetPayload), dest)
}

// GetType mocks base method.
func (m *MockEvent) GetType() event.EvType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(event.EvType)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockEventMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockEvent)(nil).GetType))
}

// Serialize mocks base method.
func (m *MockEvent) Serialize() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Serialize indicates an expected call of Serialize.
func (mr *MockEventMockRecorder) Serialize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockEvent)(nil).Serialize))
}

// MockPayload is a mock of Payload interface.
type MockPayload struct {
	ctrl     *gomock.Controller
	recorder *MockPayloadMockRecorder
	isgomock struct{}
}

// MockPayloadMockRecorder is the mock recorder for MockPayload.
type MockPayloadMockRecorder struct {
	mock *MockPayload
}

// NewMockPayload creates a new mock instance.
func NewMockPayload(ctrl *gomock.Controller) *MockPayload {
	mock := &MockPayload{ctrl: ctrl}
	mock.recorder = &MockPayloadMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayload) EXPECT() *MockPayloadMockRecorder {
	return m.recorder
}

// EventType mocks base method.
func (m *MockPayload) EventType() event.EvType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventType")
	ret0, _ := ret[0].(event.EvType)
	return ret0
}

// EventType indicates an expected call of EventType.
func (mr *MockPayloadMockRecorder) EventType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventType", reflect.TypeOf((*MockPayload)(nil).EventType))
}
