// Code generated by MockGen. DO NOT EDIT.
// Source: repository/inmem/core.go
//
// Generated by this command:
//
//	mockgen -source=repository/inmem/core.go -destination=mocks/inmem_core_mocks_test.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInMemConfig is a mock of InMemConfig interface.
type MockInMemConfig struct {
	ctrl     *gomock.Controller
	recorder *MockInMemConfigMockRecorder
	isgomock struct{}
}

// MockInMemConfigMockRecorder is the mock recorder for MockInMemConfig.
type MockInMemConfigMockRecorder struct {
	mock *MockInMemConfig
}

// NewMockInMemConfig creates a new mock instance.
func NewMockInMemConfig(ctrl *gomock.Controller) *MockInMemConfig {
	mock := &MockInMemConfig{ctrl: ctrl}
	mock.recorder = &MockInMemConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemConfig) EXPECT() *MockInMemConfigMockRecorder {
	return m.recorder
}

// ShardSize mocks base method.
func (m *MockInMemConfig) ShardSize() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardSize")
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardSize indicates an expected call of ShardSize.
func (mr *MockInMemConfigMockRecorder) ShardSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardSize", reflect.TypeOf((*MockInMemConfig)(nil).ShardSize))
}
