// Code generated by MockGen. DO NOT EDIT.
// Source: model/jwtmanager/jwtmanager.go
//
// Generated by this command:
//
//	mockgen -source=model/jwtmanager/jwtmanager.go -destination=mocks/jwtmanager_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockJWTManagerConfig is a mock of JWTManagerConfig interface.
type MockJWTManagerConfig struct {
	ctrl     *gomock.Controller
	recorder *MockJWTManagerConfigMockRecorder
	isgomock struct{}
}

// MockJWTManagerConfigMockRecorder is the mock recorder for MockJWTManagerConfig.
type MockJWTManagerConfigMockRecorder struct {
	mock *MockJWTManagerConfig
}

// NewMockJWTManagerConfig creates a new mock instance.
func NewMockJWTManagerConfig(ctrl *gomock.Controller) *MockJWTManagerConfig {
	mock := &MockJWTManagerConfig{ctrl: ctrl}
	mock.recorder = &MockJWTManagerConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTManagerConfig) EXPECT() *MockJWTManagerConfigMockRecorder {
	return m.recorder
}

// JWTSecretKey mocks base method.
func (m *MockJWTManagerConfig) JWTSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JWTSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// JWTSecretKey indicates an expected call of JWTSecretKey.
func (mr *MockJWTManagerConfigMockRecorder) JWTSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWTSecretKey", reflect.TypeOf((*MockJWTManagerConfig)(nil).JWTSecretKey))
}

// JWTTTL mocks base method.
func (m *MockJWTManagerConfig) JWTTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JWTTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// JWTTTL indicates an expected call of JWTTTL.
func (mr *MockJWTManagerConfigMockRecorder) JWTTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWTTTL", reflect.TypeOf((*MockJWTManagerConfig)(nil).JWTTTL))
}
