// Code generated by MockGen. DO NOT EDIT.
// Source: repository/pgc/pg_cluster.go
//
// Generated by this command:
//
//	mockgen -source=repository/pgc/pg_cluster.go -destination=mocks/pgc_pgcluster_mocks_test.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	instance "murl/internal/repository/pgc/instance"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPgClusterConfig is a mock of PgClusterConfig interface.
type MockPgClusterConfig struct {
	ctrl     *gomock.Controller
	recorder *MockPgClusterConfigMockRecorder
	isgomock struct{}
}

// MockPgClusterConfigMockRecorder is the mock recorder for MockPgClusterConfig.
type MockPgClusterConfigMockRecorder struct {
	mock *MockPgClusterConfig
}

// NewMockPgClusterConfig creates a new mock instance.
func NewMockPgClusterConfig(ctrl *gomock.Controller) *MockPgClusterConfig {
	mock := &MockPgClusterConfig{ctrl: ctrl}
	mock.recorder = &MockPgClusterConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgClusterConfig) EXPECT() *MockPgClusterConfigMockRecorder {
	return m.recorder
}

// DBDSN mocks base method.
func (m *MockPgClusterConfig) DBDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DBDSN indicates an expected call of DBDSN.
func (mr *MockPgClusterConfigMockRecorder) DBDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBDSN", reflect.TypeOf((*MockPgClusterConfig)(nil).DBDSN))
}

// ShardSize mocks base method.
func (m *MockPgClusterConfig) ShardSize() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardSize")
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardSize indicates an expected call of ShardSize.
func (mr *MockPgClusterConfigMockRecorder) ShardSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardSize", reflect.TypeOf((*MockPgClusterConfig)(nil).ShardSize))
}

// MockPgCluster is a mock of PgCluster interface.
type MockPgCluster struct {
	ctrl     *gomock.Controller
	recorder *MockPgClusterMockRecorder
	isgomock struct{}
}

// MockPgClusterMockRecorder is the mock recorder for MockPgCluster.
type MockPgClusterMockRecorder struct {
	mock *MockPgCluster
}

// NewMockPgCluster creates a new mock instance.
func NewMockPgCluster(ctrl *gomock.Controller) *MockPgCluster {
	mock := &MockPgCluster{ctrl: ctrl}
	mock.recorder = &MockPgClusterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgCluster) EXPECT() *MockPgClusterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPgCluster) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPgClusterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPgCluster)(nil).Close))
}

// GetShard mocks base method.
func (m *MockPgCluster) GetShard(shardID byte) (*instance.PgInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShard", shardID)
	ret0, _ := ret[0].(*instance.PgInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShard indicates an expected call of GetShard.
func (mr *MockPgClusterMockRecorder) GetShard(shardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShard", reflect.TypeOf((*MockPgCluster)(nil).GetShard), shardID)
}

// Ping mocks base method.
func (m *MockPgCluster) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPgClusterMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPgCluster)(nil).Ping), ctx)
}

// RunMigrations mocks base method.
func (m *MockPgCluster) RunMigrations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrations indicates an expected call of RunMigrations.
func (mr *MockPgClusterMockRecorder) RunMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrations", reflect.TypeOf((*MockPgCluster)(nil).RunMigrations), ctx)
}

// ShardID mocks base method.
func (m *MockPgCluster) ShardID(key any) byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardID", key)
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardID indicates an expected call of ShardID.
func (mr *MockPgClusterMockRecorder) ShardID(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardID", reflect.TypeOf((*MockPgCluster)(nil).ShardID), key)
}

// Size mocks base method.
func (m *MockPgCluster) Size() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(byte)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockPgClusterMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockPgCluster)(nil).Size))
}
