// Code generated by MockGen. DO NOT EDIT.
// Source: repository/pgc/metrics/prometheus_metrics.go
//
// Generated by this command:
//
//	mockgen -source=repository/pgc/metrics/prometheus_metrics.go -destination=mocks/pgc_metrics_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
