// Code generated by MockGen. DO NOT EDIT.
// Source: repository/repo_links.go
//
// Generated by this command:
//
//	mockgen -source=repository/repo_links.go -destination=mocks/repo_links_mocks_test.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	event "murl/internal/model/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepoLinks is a mock of RepoLinks interface.
type MockRepoLinks struct {
	ctrl     *gomock.Controller
	recorder *MockRepoLinksMockRecorder
	isgomock struct{}
}

// MockRepoLinksMockRecorder is the mock recorder for MockRepoLinks.
type MockRepoLinksMockRecorder struct {
	mock *MockRepoLinks
}

// NewMockRepoLinks creates a new mock instance.
func NewMockRepoLinks(ctrl *gomock.Controller) *MockRepoLinks {
	mock := &MockRepoLinks{ctrl: ctrl}
	mock.recorder = &MockRepoLinksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoLinks) EXPECT() *MockRepoLinksMockRecorder {
	return m.recorder
}

// BatchUpSert mocks base method.
func (m *MockRepoLinks) BatchUpSert(ctx context.Context, batch event.PayloadBatch) event.PayloadBatch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpSert", ctx, batch)
	ret0, _ := ret[0].(event.PayloadBatch)
	return ret0
}

// BatchUpSert indicates an expected call of BatchUpSert.
func (mr *MockRepoLinksMockRecorder) BatchUpSert(ctx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpSert", reflect.TypeOf((*MockRepoLinks)(nil).BatchUpSert), ctx, batch)
}

// Select mocks base method.
func (m *MockRepoLinks) Select(ctx context.Context, shortPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, shortPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepoLinksMockRecorder) Select(ctx, shortPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepoLinks)(nil).Select), ctx, shortPath)
}

// Set mocks base method.
func (m *MockRepoLinks) Set(ctx context.Context, longURL, shortPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, longURL, shortPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRepoLinksMockRecorder) Set(ctx, longURL, shortPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRepoLinks)(nil).Set), ctx, longURL, shortPath)
}

// UpSert mocks base method.
func (m *MockRepoLinks) UpSert(ctx context.Context, longURL string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpSert", ctx, longURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpSert indicates an expected call of UpSert.
func (mr *MockRepoLinksMockRecorder) UpSert(ctx, longURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpSert", reflect.TypeOf((*MockRepoLinks)(nil).UpSert), ctx, longURL)
}
