// Code generated by MockGen. DO NOT EDIT.
// Source: service/service.go
//
// Generated by this command:
//
//	mockgen -source=service/service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	config "murl/internal/config"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceConfig is a mock of ServiceConfig interface.
type MockServiceConfig struct {
	ctrl     *gomock.Controller
	recorder *MockServiceConfigMockRecorder
	isgomock struct{}
}

// MockServiceConfigMockRecorder is the mock recorder for MockServiceConfig.
type MockServiceConfigMockRecorder struct {
	mock *MockServiceConfig
}

// NewMockServiceConfig creates a new mock instance.
func NewMockServiceConfig(ctrl *gomock.Controller) *MockServiceConfig {
	mock := &MockServiceConfig{ctrl: ctrl}
	mock.recorder = &MockServiceConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceConfig) EXPECT() *MockServiceConfigMockRecorder {
	return m.recorder
}

// KeySession mocks base method.
func (m *MockServiceConfig) KeySession() config.KeySession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeySession")
	ret0, _ := ret[0].(config.KeySession)
	return ret0
}

// KeySession indicates an expected call of KeySession.
func (mr *MockServiceConfigMockRecorder) KeySession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeySession", reflect.TypeOf((*MockServiceConfig)(nil).KeySession))
}

// ShortBaseURL mocks base method.
func (m *MockServiceConfig) ShortBaseURL() config.ShortBaseURL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortBaseURL")
	ret0, _ := ret[0].(config.ShortBaseURL)
	return ret0
}

// ShortBaseURL indicates an expected call of ShortBaseURL.
func (mr *MockServiceConfigMockRecorder) ShortBaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortBaseURL", reflect.TypeOf((*MockServiceConfig)(nil).ShortBaseURL))
}
