// Code generated by MockGen. DO NOT EDIT.
// Source: handlers/middleware/session.go
//
// Generated by this command:
//
//	mockgen -source=handlers/middleware/session.go -destination=mocks/session_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "murl/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenManager is a mock of TokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
	isgomock struct{}
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// GenerateJWT mocks base method.
func (m *MockTokenManager) GenerateJWT(session model.Session) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWT", session)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWT indicates an expected call of GenerateJWT.
func (mr *MockTokenManagerMockRecorder) GenerateJWT(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWT", reflect.TypeOf((*MockTokenManager)(nil).GenerateJWT), session)
}

// NeedRemaining mocks base method.
func (m *MockTokenManager) NeedRemaining(session model.Session) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedRemaining", session)
	ret0, _ := ret[0].(bool)
	return ret0
}

// NeedRemaining indicates an expected call of NeedRemaining.
func (mr *MockTokenManagerMockRecorder) NeedRemaining(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedRemaining", reflect.TypeOf((*MockTokenManager)(nil).NeedRemaining), session)
}

// VerifyJWT mocks base method.
func (m *MockTokenManager) VerifyJWT(token string) (model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyJWT", token)
	ret0, _ := ret[0].(model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyJWT indicates an expected call of VerifyJWT.
func (mr *MockTokenManagerMockRecorder) VerifyJWT(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyJWT", reflect.TypeOf((*MockTokenManager)(nil).VerifyJWT), token)
}

// MockSessionConfig is a mock of SessionConfig interface.
type MockSessionConfig struct {
	ctrl     *gomock.Controller
	recorder *MockSessionConfigMockRecorder
	isgomock struct{}
}

// MockSessionConfigMockRecorder is the mock recorder for MockSessionConfig.
type MockSessionConfigMockRecorder struct {
	mock *MockSessionConfig
}

// NewMockSessionConfig creates a new mock instance.
func NewMockSessionConfig(ctrl *gomock.Controller) *MockSessionConfig {
	mock := &MockSessionConfig{ctrl: ctrl}
	mock.recorder = &MockSessionConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionConfig) EXPECT() *MockSessionConfigMockRecorder {
	return m.recorder
}

// JWTSecretKey mocks base method.
func (m *MockSessionConfig) JWTSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JWTSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// JWTSecretKey indicates an expected call of JWTSecretKey.
func (mr *MockSessionConfigMockRecorder) JWTSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWTSecretKey", reflect.TypeOf((*MockSessionConfig)(nil).JWTSecretKey))
}

// JWTTTL mocks base method.
func (m *MockSessionConfig) JWTTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JWTTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// JWTTTL indicates an expected call of JWTTTL.
func (mr *MockSessionConfigMockRecorder) JWTTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWTTTL", reflect.TypeOf((*MockSessionConfig)(nil).JWTTTL))
}

// KeySession mocks base method.
func (m *MockSessionConfig) KeySession() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeySession")
	ret0, _ := ret[0].(string)
	return ret0
}

// KeySession indicates an expected call of KeySession.
func (mr *MockSessionConfigMockRecorder) KeySession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeySession", reflect.TypeOf((*MockSessionConfig)(nil).KeySession))
}
