// Code generated by MockGen. DO NOT EDIT.
// Source: wal.go
//
// Generated by this command:
//
//	mockgen -source=wal.go -destination=wal_mock_test.go -package=wal
//

// Package wal is a generated GoMock package.
package wal

import (
	event "murl/internal/model/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWAL is a mock of WAL interface.
type MockWAL struct {
	ctrl     *gomock.Controller
	recorder *MockWALMockRecorder
	isgomock struct{}
}

// MockWALMockRecorder is the mock recorder for MockWAL.
type MockWALMockRecorder struct {
	mock *MockWAL
}

// NewMockWAL creates a new mock instance.
func NewMockWAL(ctrl *gomock.Controller) *MockWAL {
	mock := &MockWAL{ctrl: ctrl}
	mock.recorder = &MockWALMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWAL) EXPECT() *MockWALMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWAL) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWALMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWAL)(nil).Close))
}

// Push mocks base method.
func (m *MockWAL) Push(e event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockWALMockRecorder) Push(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockWAL)(nil).Push), e)
}
