// Code generated by MockGen. DO NOT EDIT.
// Source: pg_batch_exec.go
//
// Generated by this command:
//
//	mockgen -source=pg_batch_exec.go -destination=pg_batch_exec_mock_test.go -package=pgbatch
//

// Package pgbatch is a generated GoMock package.
package pgbatch
