// Code generated by MockGen. DO NOT EDIT.
// Source: ../../adapters/pgc/pgc.go
//
// Generated by this command:
//
//	mockgen -source=../../adapters/pgc/pgc.go -destination=repo_impl_pgc_mock_test.go -package=repo
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	iter "iter"
	slog "log/slog"
	pgc "murl/internal/adapters/pgc"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	trace "go.opentelemetry.io/otel/trace"
	gomock "go.uber.org/mock/gomock"
)

// MockPgQuery is a mock of PgQuery interface.
type MockPgQuery struct {
	ctrl     *gomock.Controller
	recorder *MockPgQueryMockRecorder
	isgomock struct{}
}

// MockPgQueryMockRecorder is the mock recorder for MockPgQuery.
type MockPgQueryMockRecorder struct {
	mock *MockPgQuery
}

// NewMockPgQuery creates a new mock instance.
func NewMockPgQuery(ctrl *gomock.Controller) *MockPgQuery {
	mock := &MockPgQuery{ctrl: ctrl}
	mock.recorder = &MockPgQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgQuery) EXPECT() *MockPgQueryMockRecorder {
	return m.recorder
}

// Binder mocks base method.
func (m *MockPgQuery) Binder(target any) []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Binder", target)
	ret0, _ := ret[0].([]any)
	return ret0
}

// Binder indicates an expected call of Binder.
func (mr *MockPgQueryMockRecorder) Binder(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Binder", reflect.TypeOf((*MockPgQuery)(nil).Binder), target)
}

// HasReturns mocks base method.
func (m *MockPgQuery) HasReturns() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasReturns")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasReturns indicates an expected call of HasReturns.
func (mr *MockPgQueryMockRecorder) HasReturns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasReturns", reflect.TypeOf((*MockPgQuery)(nil).HasReturns))
}

// IsReadOnly mocks base method.
func (m *MockPgQuery) IsReadOnly() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReadOnly")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReadOnly indicates an expected call of IsReadOnly.
func (mr *MockPgQueryMockRecorder) IsReadOnly() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadOnly", reflect.TypeOf((*MockPgQuery)(nil).IsReadOnly))
}

// Name mocks base method.
func (m *MockPgQuery) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPgQueryMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPgQuery)(nil).Name))
}

// NewTarget mocks base method.
func (m *MockPgQuery) NewTarget() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTarget")
	ret0, _ := ret[0].(any)
	return ret0
}

// NewTarget indicates an expected call of NewTarget.
func (mr *MockPgQueryMockRecorder) NewTarget() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTarget", reflect.TypeOf((*MockPgQuery)(nil).NewTarget))
}

// SQL mocks base method.
func (m *MockPgQuery) SQL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SQL")
	ret0, _ := ret[0].(string)
	return ret0
}

// SQL indicates an expected call of SQL.
func (mr *MockPgQueryMockRecorder) SQL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SQL", reflect.TypeOf((*MockPgQuery)(nil).SQL))
}

// MockPgInstance is a mock of PgInstance interface.
type MockPgInstance struct {
	ctrl     *gomock.Controller
	recorder *MockPgInstanceMockRecorder
	isgomock struct{}
}

// MockPgInstanceMockRecorder is the mock recorder for MockPgInstance.
type MockPgInstanceMockRecorder struct {
	mock *MockPgInstance
}

// NewMockPgInstance creates a new mock instance.
func NewMockPgInstance(ctrl *gomock.Controller) *MockPgInstance {
	mock := &MockPgInstance{ctrl: ctrl}
	mock.recorder = &MockPgInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgInstance) EXPECT() *MockPgInstanceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPgInstance) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPgInstanceMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPgInstance)(nil).Close), ctx)
}

// Exec mocks base method.
func (m *MockPgInstance) Exec(ctx context.Context, q pgc.PgQuery, args ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, q}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockPgInstanceMockRecorder) Exec(ctx, q any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, q}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPgInstance)(nil).Exec), varargs...)
}

// Fetch mocks base method.
func (m *MockPgInstance) Fetch(ctx context.Context, q pgc.PgQuery, args ...any) iter.Seq2[any, error] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, q}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Fetch", varargs...)
	ret0, _ := ret[0].(iter.Seq2[any, error])
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockPgInstanceMockRecorder) Fetch(ctx, q any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, q}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockPgInstance)(nil).Fetch), varargs...)
}

// FetchRow mocks base method.
func (m *MockPgInstance) FetchRow(ctx context.Context, q pgc.PgQuery, args ...any) (any, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, q}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchRow", varargs...)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRow indicates an expected call of FetchRow.
func (mr *MockPgInstanceMockRecorder) FetchRow(ctx, q any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, q}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRow", reflect.TypeOf((*MockPgInstance)(nil).FetchRow), varargs...)
}

// IsOnline mocks base method.
func (m *MockPgInstance) IsOnline() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOnline")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOnline indicates an expected call of IsOnline.
func (mr *MockPgInstanceMockRecorder) IsOnline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOnline", reflect.TypeOf((*MockPgInstance)(nil).IsOnline))
}

// Ping mocks base method.
func (m *MockPgInstance) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPgInstanceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPgInstance)(nil).Ping), ctx)
}

// RunMigrations mocks base method.
func (m *MockPgInstance) RunMigrations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrations indicates an expected call of RunMigrations.
func (mr *MockPgInstanceMockRecorder) RunMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrations", reflect.TypeOf((*MockPgInstance)(nil).RunMigrations), ctx)
}

// SendBatch mocks base method.
func (m *MockPgInstance) SendBatch(ctx context.Context, q pgc.PgQuery, args [][]any) iter.Seq2[any, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, q, args)
	ret0, _ := ret[0].(iter.Seq2[any, error])
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockPgInstanceMockRecorder) SendBatch(ctx, q, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockPgInstance)(nil).SendBatch), ctx, q, args)
}

// String mocks base method.
func (m *MockPgInstance) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockPgInstanceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockPgInstance)(nil).String))
}

// WithMeterProvider mocks base method.
func (m *MockPgInstance) WithMeterProvider(arg0 metric.MeterProvider) pgc.PgInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithMeterProvider", arg0)
	ret0, _ := ret[0].(pgc.PgInstance)
	return ret0
}

// WithMeterProvider indicates an expected call of WithMeterProvider.
func (mr *MockPgInstanceMockRecorder) WithMeterProvider(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithMeterProvider", reflect.TypeOf((*MockPgInstance)(nil).WithMeterProvider), arg0)
}

// WithSlogHandler mocks base method.
func (m *MockPgInstance) WithSlogHandler(arg0 slog.Handler) pgc.PgInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSlogHandler", arg0)
	ret0, _ := ret[0].(pgc.PgInstance)
	return ret0
}

// WithSlogHandler indicates an expected call of WithSlogHandler.
func (mr *MockPgInstanceMockRecorder) WithSlogHandler(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSlogHandler", reflect.TypeOf((*MockPgInstance)(nil).WithSlogHandler), arg0)
}

// WithTracerProvider mocks base method.
func (m *MockPgInstance) WithTracerProvider(arg0 trace.TracerProvider) pgc.PgInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTracerProvider", arg0)
	ret0, _ := ret[0].(pgc.PgInstance)
	return ret0
}

// WithTracerProvider indicates an expected call of WithTracerProvider.
func (mr *MockPgInstanceMockRecorder) WithTracerProvider(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTracerProvider", reflect.TypeOf((*MockPgInstance)(nil).WithTracerProvider), arg0)
}
