// Code generated by MockGen. DO NOT EDIT.
// Source: ../pgc/instance/pg_instance_impl.go
//
// Generated by this command:
//
//	mockgen -source=../pgc/instance/pg_instance_impl.go -destination=repo_impl_pg_instance_impl_mock_test.go -package=repo
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	gomock "go.uber.org/mock/gomock"
)

// MockpgxPoolDriverIface is a mock of pgxPoolDriverIface interface.
type MockpgxPoolDriverIface struct {
	ctrl     *gomock.Controller
	recorder *MockpgxPoolDriverIfaceMockRecorder
	isgomock struct{}
}

// MockpgxPoolDriverIfaceMockRecorder is the mock recorder for MockpgxPoolDriverIface.
type MockpgxPoolDriverIfaceMockRecorder struct {
	mock *MockpgxPoolDriverIface
}

// NewMockpgxPoolDriverIface creates a new mock instance.
func NewMockpgxPoolDriverIface(ctrl *gomock.Controller) *MockpgxPoolDriverIface {
	mock := &MockpgxPoolDriverIface{ctrl: ctrl}
	mock.recorder = &MockpgxPoolDriverIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpgxPoolDriverIface) EXPECT() *MockpgxPoolDriverIfaceMockRecorder {
	return m.recorder
}

// AsPool mocks base method.
func (m *MockpgxPoolDriverIface) AsPool() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsPool")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// AsPool indicates an expected call of AsPool.
func (mr *MockpgxPoolDriverIfaceMockRecorder) AsPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsPool", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).AsPool))
}

// Begin mocks base method.
func (m *MockpgxPoolDriverIface) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockpgxPoolDriverIfaceMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).Begin), ctx)
}

// Close mocks base method.
func (m *MockpgxPoolDriverIface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockpgxPoolDriverIfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).Close))
}

// CopyFrom mocks base method.
func (m *MockpgxPoolDriverIface) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockpgxPoolDriverIfaceMockRecorder) CopyFrom(ctx, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).CopyFrom), ctx, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockpgxPoolDriverIface) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockpgxPoolDriverIfaceMockRecorder) Exec(ctx, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).Exec), varargs...)
}

// Ping mocks base method.
func (m *MockpgxPoolDriverIface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockpgxPoolDriverIfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).Ping), ctx)
}

// Query mocks base method.
func (m *MockpgxPoolDriverIface) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockpgxPoolDriverIfaceMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockpgxPoolDriverIface) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockpgxPoolDriverIfaceMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).QueryRow), varargs...)
}

// SendBatch mocks base method.
func (m *MockpgxPoolDriverIface) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockpgxPoolDriverIfaceMockRecorder) SendBatch(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).SendBatch), ctx, b)
}

// Stat mocks base method.
func (m *MockpgxPoolDriverIface) Stat() *pgxpool.Stat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(*pgxpool.Stat)
	return ret0
}

// Stat indicates an expected call of Stat.
func (mr *MockpgxPoolDriverIfaceMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockpgxPoolDriverIface)(nil).Stat))
}
