-- +goose Up
-- +goose StatementBegin
DO $$ 
BEGIN
    -- 1. Создаем таблицу
    CREATE TABLE IF NOT EXISTS murl (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        url TEXT NOT NULL,
        CONSTRAINT idx_murl_url UNIQUE (url)
    );

    -- 2. Если есть бэкап от предыдущего Down, восстанавливаем его
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'murl_backup_down_0001') THEN
        INSERT INTO murl (id, url) 
        SELECT id, url FROM murl_backup_down_0001
        ON CONFLICT (url) DO NOTHING;
        
        -- Синхронизируем счетчик IDENTITY с максимальным вставленным ID
        -- Для IDENTITY это делается через RESTART с подзапросом
        EXECUTE format('ALTER TABLE murl ALTER COLUMN id RESTART WITH %s', 
            (SELECT coalesce(max(id), 0) + 1 FROM murl));
        
        DROP TABLE IF EXISTS murl_backup_down_0001;
        RAISE NOTICE 'Data restored from murl_backup_down_0001 and sequence restarted.';
    END IF;
END $$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ 
DECLARE
    has_data boolean;
BEGIN
    -- Проверяем наличие данных
    SELECT EXISTS (SELECT 1 FROM murl LIMIT 1) INTO has_data;

    IF has_data THEN
        -- Создаем бэкап (структура BIGINT и данные сохранятся автоматически)
        DROP TABLE IF EXISTS murl_backup_down_0001;
        CREATE TABLE IF NOT EXISTS murl_backup_down_0001 AS 
        SELECT * FROM murl;
        
        RAISE NOTICE 'Backup created: murl_backup_down_0001 (BIGINT ID preserved)';
    END IF;

    DROP TABLE IF EXISTS murl;
END $$;
-- +goose StatementEnd
