// Code generated by MockGen. DO NOT EDIT.
// Source: repo_drv.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
)

// MockRepoDrvConfig is a mock of RepoDrvConfig interface.
type MockRepoDrvConfig struct {
	ctrl     *gomock.Controller
	recorder *MockRepoDrvConfigMockRecorder
}

// MockRepoDrvConfigMockRecorder is the mock recorder for MockRepoDrvConfig.
type MockRepoDrvConfigMockRecorder struct {
	mock *MockRepoDrvConfig
}

// NewMockRepoDrvConfig creates a new mock instance.
func NewMockRepoDrvConfig(ctrl *gomock.Controller) *MockRepoDrvConfig {
	mock := &MockRepoDrvConfig{ctrl: ctrl}
	mock.recorder = &MockRepoDrvConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoDrvConfig) EXPECT() *MockRepoDrvConfigMockRecorder {
	return m.recorder
}

// DBDSN mocks base method.
func (m *MockRepoDrvConfig) DBDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DBDSN indicates an expected call of DBDSN.
func (mr *MockRepoDrvConfigMockRecorder) DBDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBDSN", reflect.TypeOf((*MockRepoDrvConfig)(nil).DBDSN))
}

// EventStoragePath mocks base method.
func (m *MockRepoDrvConfig) EventStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventStoragePath indicates an expected call of EventStoragePath.
func (mr *MockRepoDrvConfigMockRecorder) EventStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventStoragePath", reflect.TypeOf((*MockRepoDrvConfig)(nil).EventStoragePath))
}

// RepoDrv mocks base method.
func (m *MockRepoDrvConfig) RepoDrv() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoDrv")
	ret0, _ := ret[0].(string)
	return ret0
}

// RepoDrv indicates an expected call of RepoDrv.
func (mr *MockRepoDrvConfigMockRecorder) RepoDrv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoDrv", reflect.TypeOf((*MockRepoDrvConfig)(nil).RepoDrv))
}

// ShardSize mocks base method.
func (m *MockRepoDrvConfig) ShardSize() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardSize")
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardSize indicates an expected call of ShardSize.
func (mr *MockRepoDrvConfigMockRecorder) ShardSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardSize", reflect.TypeOf((*MockRepoDrvConfig)(nil).ShardSize))
}

// MockRepoDrv is a mock of RepoDrv interface.
type MockRepoDrv struct {
	ctrl     *gomock.Controller
	recorder *MockRepoDrvMockRecorder
}

// MockRepoDrvMockRecorder is the mock recorder for MockRepoDrv.
type MockRepoDrvMockRecorder struct {
	mock *MockRepoDrv
}

// NewMockRepoDrv creates a new mock instance.
func NewMockRepoDrv(ctrl *gomock.Controller) *MockRepoDrv {
	mock := &MockRepoDrv{ctrl: ctrl}
	mock.recorder = &MockRepoDrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoDrv) EXPECT() *MockRepoDrvMockRecorder {
	return m.recorder
}

// Select mocks base method.
func (m *MockRepoDrv) Select(ctx context.Context, shardID byte, idx uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, shardID, idx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepoDrvMockRecorder) Select(ctx, shardID, idx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepoDrv)(nil).Select), ctx, shardID, idx)
}

// Set mocks base method.
func (m *MockRepoDrv) Set(ctx context.Context, shardID byte, idx uint64, u string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, shardID, idx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRepoDrvMockRecorder) Set(ctx, shardID, idx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRepoDrv)(nil).Set), ctx, shardID, idx, u)
}

// UpSert mocks base method.
func (m *MockRepoDrv) UpSert(ctx context.Context, shardID byte, str string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpSert", ctx, shardID, str)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpSert indicates an expected call of UpSert.
func (mr *MockRepoDrvMockRecorder) UpSert(ctx, shardID, str interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpSert", reflect.TypeOf((*MockRepoDrv)(nil).UpSert), ctx, shardID, str)
}

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// PgPool mocks base method.
func (m *MockDBHandler) PgPool(ctx context.Context, cb func(context.Context, *pgxpool.Pool) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PgPool", ctx, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// PgPool indicates an expected call of PgPool.
func (mr *MockDBHandlerMockRecorder) PgPool(ctx, cb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PgPool", reflect.TypeOf((*MockDBHandler)(nil).PgPool), ctx, cb)
}

// Tx mocks base method.
func (m *MockDBHandler) Tx(ctx context.Context, cb func(context.Context, pgx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tx", ctx, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// Tx indicates an expected call of Tx.
func (mr *MockDBHandlerMockRecorder) Tx(ctx, cb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tx", reflect.TypeOf((*MockDBHandler)(nil).Tx), ctx, cb)
}
