// Code generated by MockGen. DO NOT EDIT.
// Source: repo_stats.go
//
// Generated by this command:
//
//	mockgen -source=repo_stats.go -destination=repo_stats_mock_test.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	dto "murl/internal/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepoStats is a mock of RepoStats interface.
type MockRepoStats struct {
	ctrl     *gomock.Controller
	recorder *MockRepoStatsMockRecorder
	isgomock struct{}
}

// MockRepoStatsMockRecorder is the mock recorder for MockRepoStats.
type MockRepoStatsMockRecorder struct {
	mock *MockRepoStats
}

// NewMockRepoStats creates a new mock instance.
func NewMockRepoStats(ctrl *gomock.Controller) *MockRepoStats {
	mock := &MockRepoStats{ctrl: ctrl}
	mock.recorder = &MockRepoStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoStats) EXPECT() *MockRepoStatsMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockRepoStats) GetStats(ctx context.Context) (dto.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(dto.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRepoStatsMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRepoStats)(nil).GetStats), ctx)
}
