// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=repo_mock_test.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	event "murl/internal/model/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepoConfig is a mock of RepoConfig interface.
type MockRepoConfig struct {
	ctrl     *gomock.Controller
	recorder *MockRepoConfigMockRecorder
	isgomock struct{}
}

// MockRepoConfigMockRecorder is the mock recorder for MockRepoConfig.
type MockRepoConfigMockRecorder struct {
	mock *MockRepoConfig
}

// NewMockRepoConfig creates a new mock instance.
func NewMockRepoConfig(ctrl *gomock.Controller) *MockRepoConfig {
	mock := &MockRepoConfig{ctrl: ctrl}
	mock.recorder = &MockRepoConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoConfig) EXPECT() *MockRepoConfigMockRecorder {
	return m.recorder
}

// DBDSN mocks base method.
func (m *MockRepoConfig) DBDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DBDSN indicates an expected call of DBDSN.
func (mr *MockRepoConfigMockRecorder) DBDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBDSN", reflect.TypeOf((*MockRepoConfig)(nil).DBDSN))
}

// EventStoragePath mocks base method.
func (m *MockRepoConfig) EventStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventStoragePath indicates an expected call of EventStoragePath.
func (mr *MockRepoConfigMockRecorder) EventStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventStoragePath", reflect.TypeOf((*MockRepoConfig)(nil).EventStoragePath))
}

// RepoDrv mocks base method.
func (m *MockRepoConfig) RepoDrv() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoDrv")
	ret0, _ := ret[0].(string)
	return ret0
}

// RepoDrv indicates an expected call of RepoDrv.
func (mr *MockRepoConfigMockRecorder) RepoDrv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoDrv", reflect.TypeOf((*MockRepoConfig)(nil).RepoDrv))
}

// ShardSize mocks base method.
func (m *MockRepoConfig) ShardSize() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardSize")
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardSize indicates an expected call of ShardSize.
func (mr *MockRepoConfigMockRecorder) ShardSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardSize", reflect.TypeOf((*MockRepoConfig)(nil).ShardSize))
}

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepo) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRepoMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepo)(nil).Close))
}

// On mocks base method.
func (m *MockRepo) On(ctx context.Context, e event.Event) (event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "On", ctx, e)
	ret0, _ := ret[0].(event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// On indicates an expected call of On.
func (mr *MockRepoMockRecorder) On(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "On", reflect.TypeOf((*MockRepo)(nil).On), ctx, e)
}

// Ping mocks base method.
func (m *MockRepo) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepoMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepo)(nil).Ping), ctx)
}
