// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepoConfig is a mock of RepoConfig interface.
type MockRepoConfig struct {
	ctrl     *gomock.Controller
	recorder *MockRepoConfigMockRecorder
}

// MockRepoConfigMockRecorder is the mock recorder for MockRepoConfig.
type MockRepoConfigMockRecorder struct {
	mock *MockRepoConfig
}

// NewMockRepoConfig creates a new mock instance.
func NewMockRepoConfig(ctrl *gomock.Controller) *MockRepoConfig {
	mock := &MockRepoConfig{ctrl: ctrl}
	mock.recorder = &MockRepoConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoConfig) EXPECT() *MockRepoConfigMockRecorder {
	return m.recorder
}

// DBDSN mocks base method.
func (m *MockRepoConfig) DBDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DBDSN indicates an expected call of DBDSN.
func (mr *MockRepoConfigMockRecorder) DBDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBDSN", reflect.TypeOf((*MockRepoConfig)(nil).DBDSN))
}

// EventStoragePath mocks base method.
func (m *MockRepoConfig) EventStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventStoragePath indicates an expected call of EventStoragePath.
func (mr *MockRepoConfigMockRecorder) EventStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventStoragePath", reflect.TypeOf((*MockRepoConfig)(nil).EventStoragePath))
}

// RepoDrv mocks base method.
func (m *MockRepoConfig) RepoDrv() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoDrv")
	ret0, _ := ret[0].(string)
	return ret0
}

// RepoDrv indicates an expected call of RepoDrv.
func (mr *MockRepoConfigMockRecorder) RepoDrv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoDrv", reflect.TypeOf((*MockRepoConfig)(nil).RepoDrv))
}

// ShardSize mocks base method.
func (m *MockRepoConfig) ShardSize() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardSize")
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardSize indicates an expected call of ShardSize.
func (mr *MockRepoConfigMockRecorder) ShardSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardSize", reflect.TypeOf((*MockRepoConfig)(nil).ShardSize))
}

// MockRepoDataDrv is a mock of RepoDataDrv interface.
type MockRepoDataDrv struct {
	ctrl     *gomock.Controller
	recorder *MockRepoDataDrvMockRecorder
}

// MockRepoDataDrvMockRecorder is the mock recorder for MockRepoDataDrv.
type MockRepoDataDrvMockRecorder struct {
	mock *MockRepoDataDrv
}

// NewMockRepoDataDrv creates a new mock instance.
func NewMockRepoDataDrv(ctrl *gomock.Controller) *MockRepoDataDrv {
	mock := &MockRepoDataDrv{ctrl: ctrl}
	mock.recorder = &MockRepoDataDrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoDataDrv) EXPECT() *MockRepoDataDrvMockRecorder {
	return m.recorder
}

// Select mocks base method.
func (m *MockRepoDataDrv) Select(ctx context.Context, shardID byte, idx uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, shardID, idx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepoDataDrvMockRecorder) Select(ctx, shardID, idx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepoDataDrv)(nil).Select), ctx, shardID, idx)
}

// Set mocks base method.
func (m *MockRepoDataDrv) Set(ctx context.Context, shardID byte, idx uint64, u string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, shardID, idx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRepoDataDrvMockRecorder) Set(ctx, shardID, idx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRepoDataDrv)(nil).Set), ctx, shardID, idx, u)
}

// UpSert mocks base method.
func (m *MockRepoDataDrv) UpSert(ctx context.Context, shardID byte, str string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpSert", ctx, shardID, str)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpSert indicates an expected call of UpSert.
func (mr *MockRepoDataDrvMockRecorder) UpSert(ctx, shardID, str interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpSert", reflect.TypeOf((*MockRepoDataDrv)(nil).UpSert), ctx, shardID, str)
}
