// Code generated by MockGen. DO NOT EDIT.
// Source: repo_links_by_session_id.go
//
// Generated by this command:
//
//	mockgen -source=repo_links_by_session_id.go -destination=repo_links_by_session_id_mock_test.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	dto "murl/internal/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepoLinksBySessionID is a mock of RepoLinksBySessionID interface.
type MockRepoLinksBySessionID struct {
	ctrl     *gomock.Controller
	recorder *MockRepoLinksBySessionIDMockRecorder
	isgomock struct{}
}

// MockRepoLinksBySessionIDMockRecorder is the mock recorder for MockRepoLinksBySessionID.
type MockRepoLinksBySessionIDMockRecorder struct {
	mock *MockRepoLinksBySessionID
}

// NewMockRepoLinksBySessionID creates a new mock instance.
func NewMockRepoLinksBySessionID(ctrl *gomock.Controller) *MockRepoLinksBySessionID {
	mock := &MockRepoLinksBySessionID{ctrl: ctrl}
	mock.recorder = &MockRepoLinksBySessionIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoLinksBySessionID) EXPECT() *MockRepoLinksBySessionIDMockRecorder {
	return m.recorder
}

// BatchDelBySessionID mocks base method.
func (m *MockRepoLinksBySessionID) BatchDelBySessionID(ctx context.Context, sessionID string, batch dto.DeleteURLBySessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelBySessionID", ctx, sessionID, batch)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelBySessionID indicates an expected call of BatchDelBySessionID.
func (mr *MockRepoLinksBySessionIDMockRecorder) BatchDelBySessionID(ctx, sessionID, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelBySessionID", reflect.TypeOf((*MockRepoLinksBySessionID)(nil).BatchDelBySessionID), ctx, sessionID, batch)
}

// SelectAll mocks base method.
func (m *MockRepoLinksBySessionID) SelectAll(ctx context.Context, sessionID string) ([]dto.URLItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll", ctx, sessionID)
	ret0, _ := ret[0].([]dto.URLItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll.
func (mr *MockRepoLinksBySessionIDMockRecorder) SelectAll(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockRepoLinksBySessionID)(nil).SelectAll), ctx, sessionID)
}

// Set mocks base method.
func (m *MockRepoLinksBySessionID) Set(ctx context.Context, sessionID, originalURL, shortPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, sessionID, originalURL, shortPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRepoLinksBySessionIDMockRecorder) Set(ctx, sessionID, originalURL, shortPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRepoLinksBySessionID)(nil).Set), ctx, sessionID, originalURL, shortPath)
}

// UpSert mocks base method.
func (m *MockRepoLinksBySessionID) UpSert(ctx context.Context, sessionID, originalURL string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpSert", ctx, sessionID, originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpSert indicates an expected call of UpSert.
func (mr *MockRepoLinksBySessionIDMockRecorder) UpSert(ctx, sessionID, originalURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpSert", reflect.TypeOf((*MockRepoLinksBySessionID)(nil).UpSert), ctx, sessionID, originalURL)
}
