// Code generated by MockGen. DO NOT EDIT.
// Source: repo_drv.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	event "murl/internal/model/event"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepoDrvConfig is a mock of RepoDrvConfig interface.
type MockRepoDrvConfig struct {
	ctrl     *gomock.Controller
	recorder *MockRepoDrvConfigMockRecorder
}

// MockRepoDrvConfigMockRecorder is the mock recorder for MockRepoDrvConfig.
type MockRepoDrvConfigMockRecorder struct {
	mock *MockRepoDrvConfig
}

// NewMockRepoDrvConfig creates a new mock instance.
func NewMockRepoDrvConfig(ctrl *gomock.Controller) *MockRepoDrvConfig {
	mock := &MockRepoDrvConfig{ctrl: ctrl}
	mock.recorder = &MockRepoDrvConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoDrvConfig) EXPECT() *MockRepoDrvConfigMockRecorder {
	return m.recorder
}

// DBDSN mocks base method.
func (m *MockRepoDrvConfig) DBDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DBDSN indicates an expected call of DBDSN.
func (mr *MockRepoDrvConfigMockRecorder) DBDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBDSN", reflect.TypeOf((*MockRepoDrvConfig)(nil).DBDSN))
}

// EventStoragePath mocks base method.
func (m *MockRepoDrvConfig) EventStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventStoragePath indicates an expected call of EventStoragePath.
func (mr *MockRepoDrvConfigMockRecorder) EventStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventStoragePath", reflect.TypeOf((*MockRepoDrvConfig)(nil).EventStoragePath))
}

// RepoDrv mocks base method.
func (m *MockRepoDrvConfig) RepoDrv() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoDrv")
	ret0, _ := ret[0].(string)
	return ret0
}

// RepoDrv indicates an expected call of RepoDrv.
func (mr *MockRepoDrvConfigMockRecorder) RepoDrv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoDrv", reflect.TypeOf((*MockRepoDrvConfig)(nil).RepoDrv))
}

// ShardSize mocks base method.
func (m *MockRepoDrvConfig) ShardSize() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardSize")
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardSize indicates an expected call of ShardSize.
func (mr *MockRepoDrvConfigMockRecorder) ShardSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardSize", reflect.TypeOf((*MockRepoDrvConfig)(nil).ShardSize))
}

// MockRepoDrv is a mock of RepoDrv interface.
type MockRepoDrv struct {
	ctrl     *gomock.Controller
	recorder *MockRepoDrvMockRecorder
}

// MockRepoDrvMockRecorder is the mock recorder for MockRepoDrv.
type MockRepoDrvMockRecorder struct {
	mock *MockRepoDrv
}

// NewMockRepoDrv creates a new mock instance.
func NewMockRepoDrv(ctrl *gomock.Controller) *MockRepoDrv {
	mock := &MockRepoDrv{ctrl: ctrl}
	mock.recorder = &MockRepoDrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoDrv) EXPECT() *MockRepoDrvMockRecorder {
	return m.recorder
}

// BatchUpSert mocks base method.
func (m *MockRepoDrv) BatchUpSert(ctx context.Context, batch []event.PayloadBatchItem) ([]event.PayloadBatchItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpSert", ctx, batch)
	ret0, _ := ret[0].([]event.PayloadBatchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpSert indicates an expected call of BatchUpSert.
func (mr *MockRepoDrvMockRecorder) BatchUpSert(ctx, batch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpSert", reflect.TypeOf((*MockRepoDrv)(nil).BatchUpSert), ctx, batch)
}

// Close mocks base method.
func (m *MockRepoDrv) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRepoDrvMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepoDrv)(nil).Close))
}

// Ping mocks base method.
func (m *MockRepoDrv) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepoDrvMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepoDrv)(nil).Ping), ctx)
}

// RunMigrations mocks base method.
func (m *MockRepoDrv) RunMigrations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrations indicates an expected call of RunMigrations.
func (mr *MockRepoDrvMockRecorder) RunMigrations(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrations", reflect.TypeOf((*MockRepoDrv)(nil).RunMigrations), ctx)
}

// Select mocks base method.
func (m *MockRepoDrv) Select(ctx context.Context, shardID byte, idx uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, shardID, idx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRepoDrvMockRecorder) Select(ctx, shardID, idx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRepoDrv)(nil).Select), ctx, shardID, idx)
}

// Set mocks base method.
func (m *MockRepoDrv) Set(ctx context.Context, shardID byte, idx uint64, u string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, shardID, idx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRepoDrvMockRecorder) Set(ctx, shardID, idx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRepoDrv)(nil).Set), ctx, shardID, idx, u)
}

// UpSert mocks base method.
func (m *MockRepoDrv) UpSert(ctx context.Context, shardID byte, str string) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpSert", ctx, shardID, str)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpSert indicates an expected call of UpSert.
func (mr *MockRepoDrvMockRecorder) UpSert(ctx, shardID, str interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpSert", reflect.TypeOf((*MockRepoDrv)(nil).UpSert), ctx, shardID, str)
}
