// Code generated by MockGen. DO NOT EDIT.
// Source: model.go
//
// Generated by this command:
//
//	mockgen -source=model.go -destination=model_mock_test.go -package=model
//

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHashable is a mock of Hashable interface.
type MockHashable struct {
	ctrl     *gomock.Controller
	recorder *MockHashableMockRecorder
	isgomock struct{}
}

// MockHashableMockRecorder is the mock recorder for MockHashable.
type MockHashableMockRecorder struct {
	mock *MockHashable
}

// NewMockHashable creates a new mock instance.
func NewMockHashable(ctrl *gomock.Controller) *MockHashable {
	mock := &MockHashable{ctrl: ctrl}
	mock.recorder = &MockHashableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashable) EXPECT() *MockHashableMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockHashable) Hash() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockHashableMockRecorder) Hash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockHashable)(nil).Hash))
}
