package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type FieldInfo struct {
	Name     string
	Type     string
	TypeName string
	IsPtr    bool
	IsSlice  bool
	IsMap    bool
	IsStruct bool
}

type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

type Data struct {
	Pkg     string
	Imports []string
	Structs []StructInfo
}

var resetTemplate = template.Must(template.New("reset").Funcs(template.FuncMap{
	"resetField": generateResetCode,
}).Parse(`// Code generated by reset generator. DO NOT EDIT.
package {{.Pkg}}

{{if .Imports}}
import (
{{range .Imports}}	{{.}}
{{end}})
{{end}}

{{range .Structs}}
func (s *{{.Name}}) Reset() {
	if s == nil {
		return
	}
{{range .Fields}}	{{resetField . "s"}}{{end}}
}
{{end}}`))

func main() {
	rootDir := "."
	if len(os.Args) > 1 {
		rootDir = os.Args[1]
	}
	_ = filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !info.IsDir() {
			return err
		}
		if strings.HasPrefix(info.Name(), ".") || info.Name() == "vendor" {
			return filepath.SkipDir
		}
		return generateResetForPackage(path)
	})
}

func generateResetForPackage(pkgPath string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, pkgPath, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	for pkgName, pkg := range pkgs {
		var files []*ast.File
		for _, f := range pkg.Files {
			files = append(files, f)
		}

		structs, imports := findResetStructs(files)
		if len(structs) == 0 {
			continue
		}

		data := Data{Pkg: pkgName, Imports: imports, Structs: structs}
		var buf bytes.Buffer
		_ = resetTemplate.Execute(&buf, data)

		res, err := format.Source(buf.Bytes())
		if err != nil {
			res = buf.Bytes()
		}

		_ = os.WriteFile(filepath.Join(pkgPath, "reset.gen.go"), res, 0644)
	}
	return nil
}

func generateResetCode(field FieldInfo, receiver string) string {
	target := fmt.Sprintf("%s.%s", receiver, field.Name)

	if field.IsPtr {
		var subReset string
		if field.IsStruct {
			subReset = fmt.Sprintf("\t\tif r, ok := any(%s).(interface{ Reset() }); ok { r.Reset() } else { *%s = %s{} }\n", target, target, field.Type)
		} else if field.IsSlice {
			subReset = fmt.Sprintf("\t\t*%s = (*%s)[:0]\n", target, target)
		} else if field.IsMap {
			subReset = fmt.Sprintf("\t\tclear(*%s)\n", target)
		} else {
			subReset = fmt.Sprintf("\t\t*%s = %s\n", target, getZeroValue(field.TypeName))
		}
		return fmt.Sprintf("if %s != nil {\n%s\t}\n", target, subReset)
	}

	if field.IsSlice {
		return fmt.Sprintf("%s = %s[:0]\n", target, target)
	}
	if field.IsMap {
		return fmt.Sprintf("clear(%s)\n", target)
	}
	if field.IsStruct {
		return fmt.Sprintf("if r, ok := any(&%s).(interface{ Reset() }); ok { r.Reset() } else { %s = %s{} }\n", target, target, field.Type)
	}

	return fmt.Sprintf("%s = %s\n", target, getZeroValue(field.TypeName))
}

func getZeroValue(typeName string) string {
	switch typeName {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "byte", "rune":
		return "0"
	case "float32", "float64":
		return "0.0"
	default:
		return typeName + "{}"
	}
}

func findResetStructs(files []*ast.File) ([]StructInfo, []string) {
	var structs []StructInfo
	importMap := make(map[string]bool)

	for _, file := range files {
		fileHasResettable := false
		var fileStructs []StructInfo

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			hasTag := false
			if genDecl.Doc != nil {
				for _, c := range genDecl.Doc.List {
					if strings.Contains(c.Text, "generate:reset") {
						hasTag = true
						break
					}
				}
			}
			if !hasTag {
				continue
			}

			for _, spec := range genDecl.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				fileHasResettable = true
				fileStructs = append(fileStructs, parseStructFields(ts.Name.Name, st))
			}
		}

		if fileHasResettable {
			structs = append(structs, fileStructs...)
			for _, imp := range file.Imports {
				importMap[imp.Path.Value] = true
			}
		}
	}

	var imports []string
	for imp := range importMap {
		imports = append(imports, imp)
	}
	sort.Strings(imports)
	sort.Slice(structs, func(i, j int) bool { return structs[i].Name < structs[j].Name })
	return structs, imports
}

func parseStructFields(name string, st *ast.StructType) StructInfo {
	info := StructInfo{Name: name}
	if st.Fields == nil {
		return info
	}

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			fInfo := FieldInfo{}
			parseFieldType(field.Type, &fInfo)
			fInfo.Name = fInfo.TypeName
			info.Fields = append(info.Fields, fInfo)
			continue
		}
		for _, n := range field.Names {
			fInfo := FieldInfo{Name: n.Name}
			parseFieldType(field.Type, &fInfo)
			info.Fields = append(info.Fields, fInfo)
		}
	}
	return info
}

func parseFieldType(expr ast.Expr, info *FieldInfo) {
	switch t := expr.(type) {
	case *ast.StarExpr:
		info.IsPtr = true
		parseFieldType(t.X, info)
	case *ast.ArrayType:
		info.IsSlice = true
		parseFieldType(t.Elt, info)
	case *ast.MapType:
		info.IsMap = true
		parseFieldType(t.Value, info)
	case *ast.Ident:
		info.TypeName = t.Name
		if info.Type == "" {
			info.Type = t.Name
		}
		info.IsStruct = !isBasicType(t.Name)
	case *ast.SelectorExpr:
		if x, ok := t.X.(*ast.Ident); ok {
			info.Type = x.Name + "." + t.Sel.Name
			info.TypeName = t.Sel.Name
		}
		info.IsStruct = true
	}
}

func isBasicType(t string) bool {
	switch t {
	case "bool", "string", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "byte", "rune",
		"float32", "float64":
		return true
	}
	return false
}
