// Code generated by MockGen. DO NOT EDIT.
// Source: pg_cluster.go
//
// Generated by this command:
//
//	mockgen -source=pg_cluster.go -destination=pg_cluster_mock_test.go -package=pgc
//

// Package pgc is a generated GoMock package.
package pgc

import (
	context "context"
	slog "log/slog"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	trace "go.opentelemetry.io/otel/trace"
	gomock "go.uber.org/mock/gomock"
)

// MockPgCluster is a mock of PgCluster interface.
type MockPgCluster struct {
	ctrl     *gomock.Controller
	recorder *MockPgClusterMockRecorder
	isgomock struct{}
}

// MockPgClusterMockRecorder is the mock recorder for MockPgCluster.
type MockPgClusterMockRecorder struct {
	mock *MockPgCluster
}

// NewMockPgCluster creates a new mock instance.
func NewMockPgCluster(ctrl *gomock.Controller) *MockPgCluster {
	mock := &MockPgCluster{ctrl: ctrl}
	mock.recorder = &MockPgClusterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgCluster) EXPECT() *MockPgClusterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPgCluster) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPgClusterMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPgCluster)(nil).Close), ctx)
}

// GetShard mocks base method.
func (m *MockPgCluster) GetShard(shardID byte) (PgInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShard", shardID)
	ret0, _ := ret[0].(PgInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShard indicates an expected call of GetShard.
func (mr *MockPgClusterMockRecorder) GetShard(shardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShard", reflect.TypeOf((*MockPgCluster)(nil).GetShard), shardID)
}

// Ping mocks base method.
func (m *MockPgCluster) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPgClusterMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPgCluster)(nil).Ping), ctx)
}

// RunMigrations mocks base method.
func (m *MockPgCluster) RunMigrations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrations indicates an expected call of RunMigrations.
func (mr *MockPgClusterMockRecorder) RunMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrations", reflect.TypeOf((*MockPgCluster)(nil).RunMigrations), ctx)
}

// ShardID mocks base method.
func (m *MockPgCluster) ShardID(key any) byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardID", key)
	ret0, _ := ret[0].(byte)
	return ret0
}

// ShardID indicates an expected call of ShardID.
func (mr *MockPgClusterMockRecorder) ShardID(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardID", reflect.TypeOf((*MockPgCluster)(nil).ShardID), key)
}

// Size mocks base method.
func (m *MockPgCluster) Size() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(byte)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockPgClusterMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockPgCluster)(nil).Size))
}

// WithMeterProvider mocks base method.
func (m *MockPgCluster) WithMeterProvider(mp metric.MeterProvider) PgCluster {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithMeterProvider", mp)
	ret0, _ := ret[0].(PgCluster)
	return ret0
}

// WithMeterProvider indicates an expected call of WithMeterProvider.
func (mr *MockPgClusterMockRecorder) WithMeterProvider(mp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithMeterProvider", reflect.TypeOf((*MockPgCluster)(nil).WithMeterProvider), mp)
}

// WithSlogHandler mocks base method.
func (m *MockPgCluster) WithSlogHandler(h slog.Handler) PgCluster {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSlogHandler", h)
	ret0, _ := ret[0].(PgCluster)
	return ret0
}

// WithSlogHandler indicates an expected call of WithSlogHandler.
func (mr *MockPgClusterMockRecorder) WithSlogHandler(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSlogHandler", reflect.TypeOf((*MockPgCluster)(nil).WithSlogHandler), h)
}

// WithTracerProvider mocks base method.
func (m *MockPgCluster) WithTracerProvider(tp trace.TracerProvider) PgCluster {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTracerProvider", tp)
	ret0, _ := ret[0].(PgCluster)
	return ret0
}

// WithTracerProvider indicates an expected call of WithTracerProvider.
func (mr *MockPgClusterMockRecorder) WithTracerProvider(tp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTracerProvider", reflect.TypeOf((*MockPgCluster)(nil).WithTracerProvider), tp)
}
