// Code generated by MockGen. DO NOT EDIT.
// Source: pg_query.go
//
// Generated by this command:
//
//	mockgen -source=pg_query.go -destination=pg_query_mock_test.go -package=pgc
//

// Package pgc is a generated GoMock package.
package pgc
