
CREATE ROLE replicator WITH REPLICATION LOGIN ENCRYPTED PASSWORD 'replicator_pswd';

CREATE USER murl WITH PASSWORD 'murl_pswd';

CREATE DATABASE murl_00 OWNER murl;
CREATE DATABASE murl_01 OWNER murl;
CREATE DATABASE murl_02 OWNER murl;
CREATE DATABASE murl_03 OWNER murl;
CREATE DATABASE murl_04 OWNER murl;
CREATE DATABASE murl_05 OWNER murl;
CREATE DATABASE murl_06 OWNER murl;
CREATE DATABASE murl_07 OWNER murl;
CREATE DATABASE murl_08 OWNER murl;
CREATE DATABASE murl_09 OWNER murl;
CREATE DATABASE murl_10 OWNER murl;
CREATE DATABASE murl_11 OWNER murl;
CREATE DATABASE murl_12 OWNER murl;
CREATE DATABASE murl_13 OWNER murl;
CREATE DATABASE murl_14 OWNER murl;
CREATE DATABASE murl_15 OWNER murl;
CREATE DATABASE murl_16 OWNER murl;
CREATE DATABASE murl_17 OWNER murl;
CREATE DATABASE murl_18 OWNER murl;
CREATE DATABASE murl_19 OWNER murl;
CREATE DATABASE murl_20 OWNER murl;
CREATE DATABASE murl_21 OWNER murl;
CREATE DATABASE murl_22 OWNER murl;
CREATE DATABASE murl_23 OWNER murl;
CREATE DATABASE murl_24 OWNER murl;
CREATE DATABASE murl_25 OWNER murl;
CREATE DATABASE murl_26 OWNER murl;
CREATE DATABASE murl_27 OWNER murl;
CREATE DATABASE murl_28 OWNER murl;
CREATE DATABASE murl_29 OWNER murl;
