// Code generated by MockGen. DO NOT EDIT.
// Source: pghndl_util.go

// Package pgc is a generated GoMock package.
package pgc

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRetryableOperation is a mock of RetryableOperation interface.
type MockRetryableOperation struct {
	ctrl     *gomock.Controller
	recorder *MockRetryableOperationMockRecorder
}

// MockRetryableOperationMockRecorder is the mock recorder for MockRetryableOperation.
type MockRetryableOperationMockRecorder struct {
	mock *MockRetryableOperation
}

// NewMockRetryableOperation creates a new mock instance.
func NewMockRetryableOperation(ctrl *gomock.Controller) *MockRetryableOperation {
	mock := &MockRetryableOperation{ctrl: ctrl}
	mock.recorder = &MockRetryableOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetryableOperation) EXPECT() *MockRetryableOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRetryableOperation) Execute() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRetryableOperationMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRetryableOperation)(nil).Execute))
}
