// Code generated by MockGen. DO NOT EDIT.
// Source: pghndl.go

// Package pgc is a generated GoMock package.
package pgc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
)

// MockpgPoolProvider is a mock of pgPoolProvider interface.
type MockpgPoolProvider struct {
	ctrl     *gomock.Controller
	recorder *MockpgPoolProviderMockRecorder
}

// MockpgPoolProviderMockRecorder is the mock recorder for MockpgPoolProvider.
type MockpgPoolProviderMockRecorder struct {
	mock *MockpgPoolProvider
}

// NewMockpgPoolProvider creates a new mock instance.
func NewMockpgPoolProvider(ctrl *gomock.Controller) *MockpgPoolProvider {
	mock := &MockpgPoolProvider{ctrl: ctrl}
	mock.recorder = &MockpgPoolProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpgPoolProvider) EXPECT() *MockpgPoolProviderMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockpgPoolProvider) Begin(arg0 context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", arg0)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockpgPoolProviderMockRecorder) Begin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockpgPoolProvider)(nil).Begin), arg0)
}

// Close mocks base method.
func (m *MockpgPoolProvider) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockpgPoolProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockpgPoolProvider)(nil).Close))
}

// Config mocks base method.
func (m *MockpgPoolProvider) Config() *pgxpool.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*pgxpool.Config)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockpgPoolProviderMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockpgPoolProvider)(nil).Config))
}

// Ping mocks base method.
func (m *MockpgPoolProvider) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockpgPoolProviderMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockpgPoolProvider)(nil).Ping), arg0)
}
