// Code generated by MockGen. DO NOT EDIT.
// Source: audit_consumers.go
//
// Generated by this command:
//
//	mockgen -source=audit_consumers.go -destination=audit_consumers_mock_test.go -package=audit
//

// Package audit is a generated GoMock package.
package audit

import (
	auditlog "murl/internal/model/auditlog"
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditlogConfig is a mock of AuditlogConfig interface.
type MockAuditlogConfig struct {
	ctrl     *gomock.Controller
	recorder *MockAuditlogConfigMockRecorder
	isgomock struct{}
}

// MockAuditlogConfigMockRecorder is the mock recorder for MockAuditlogConfig.
type MockAuditlogConfigMockRecorder struct {
	mock *MockAuditlogConfig
}

// NewMockAuditlogConfig creates a new mock instance.
func NewMockAuditlogConfig(ctrl *gomock.Controller) *MockAuditlogConfig {
	mock := &MockAuditlogConfig{ctrl: ctrl}
	mock.recorder = &MockAuditlogConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditlogConfig) EXPECT() *MockAuditlogConfigMockRecorder {
	return m.recorder
}

// AuditFile mocks base method.
func (m *MockAuditlogConfig) AuditFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuditFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// AuditFile indicates an expected call of AuditFile.
func (mr *MockAuditlogConfigMockRecorder) AuditFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuditFile", reflect.TypeOf((*MockAuditlogConfig)(nil).AuditFile))
}

// AuditURL mocks base method.
func (m *MockAuditlogConfig) AuditURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuditURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// AuditURL indicates an expected call of AuditURL.
func (mr *MockAuditlogConfigMockRecorder) AuditURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuditURL", reflect.TypeOf((*MockAuditlogConfig)(nil).AuditURL))
}

// MockAuditlogSubscriber is a mock of AuditlogSubscriber interface.
type MockAuditlogSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockAuditlogSubscriberMockRecorder
	isgomock struct{}
}

// MockAuditlogSubscriberMockRecorder is the mock recorder for MockAuditlogSubscriber.
type MockAuditlogSubscriberMockRecorder struct {
	mock *MockAuditlogSubscriber
}

// NewMockAuditlogSubscriber creates a new mock instance.
func NewMockAuditlogSubscriber(ctrl *gomock.Controller) *MockAuditlogSubscriber {
	mock := &MockAuditlogSubscriber{ctrl: ctrl}
	mock.recorder = &MockAuditlogSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditlogSubscriber) EXPECT() *MockAuditlogSubscriberMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockAuditlogSubscriber) Register(s auditlog.Subscriber) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", s)
}

// Register indicates an expected call of Register.
func (mr *MockAuditlogSubscriberMockRecorder) Register(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuditlogSubscriber)(nil).Register), s)
}

// UnRegister mocks base method.
func (m *MockAuditlogSubscriber) UnRegister(s auditlog.Subscriber) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnRegister", s)
}

// UnRegister indicates an expected call of UnRegister.
func (mr *MockAuditlogSubscriberMockRecorder) UnRegister(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnRegister", reflect.TypeOf((*MockAuditlogSubscriber)(nil).UnRegister), s)
}
