// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	config "murl/internal/config"
	event "murl/internal/model/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceConfig is a mock of ServiceConfig interface.
type MockServiceConfig struct {
	ctrl     *gomock.Controller
	recorder *MockServiceConfigMockRecorder
	isgomock struct{}
}

// MockServiceConfigMockRecorder is the mock recorder for MockServiceConfig.
type MockServiceConfigMockRecorder struct {
	mock *MockServiceConfig
}

// NewMockServiceConfig creates a new mock instance.
func NewMockServiceConfig(ctrl *gomock.Controller) *MockServiceConfig {
	mock := &MockServiceConfig{ctrl: ctrl}
	mock.recorder = &MockServiceConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceConfig) EXPECT() *MockServiceConfigMockRecorder {
	return m.recorder
}

// ShortBaseURL mocks base method.
func (m *MockServiceConfig) ShortBaseURL() config.ShortBaseURL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortBaseURL")
	ret0, _ := ret[0].(config.ShortBaseURL)
	return ret0
}

// ShortBaseURL indicates an expected call of ShortBaseURL.
func (mr *MockServiceConfigMockRecorder) ShortBaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortBaseURL", reflect.TypeOf((*MockServiceConfig)(nil).ShortBaseURL))
}

// MockMicroURLRepo is a mock of MicroURLRepo interface.
type MockMicroURLRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMicroURLRepoMockRecorder
	isgomock struct{}
}

// MockMicroURLRepoMockRecorder is the mock recorder for MockMicroURLRepo.
type MockMicroURLRepoMockRecorder struct {
	mock *MockMicroURLRepo
}

// NewMockMicroURLRepo creates a new mock instance.
func NewMockMicroURLRepo(ctrl *gomock.Controller) *MockMicroURLRepo {
	mock := &MockMicroURLRepo{ctrl: ctrl}
	mock.recorder = &MockMicroURLRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMicroURLRepo) EXPECT() *MockMicroURLRepoMockRecorder {
	return m.recorder
}

// Batch mocks base method.
func (m *MockMicroURLRepo) Batch(ctx context.Context, e event.PayloadBatch) (event.PayloadBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Batch", ctx, e)
	ret0, _ := ret[0].(event.PayloadBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Batch indicates an expected call of Batch.
func (mr *MockMicroURLRepoMockRecorder) Batch(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*MockMicroURLRepo)(nil).Batch), ctx, e)
}

// Load mocks base method.
func (m *MockMicroURLRepo) Load(ctx context.Context, sID byte, idx uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, sID, idx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockMicroURLRepoMockRecorder) Load(ctx, sID, idx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockMicroURLRepo)(nil).Load), ctx, sID, idx)
}

// Ping mocks base method.
func (m *MockMicroURLRepo) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMicroURLRepoMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMicroURLRepo)(nil).Ping), ctx)
}

// PushEvent mocks base method.
func (m *MockMicroURLRepo) PushEvent(ctx context.Context, e event.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushEvent", ctx, e)
}

// PushEvent indicates an expected call of PushEvent.
func (mr *MockMicroURLRepoMockRecorder) PushEvent(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushEvent", reflect.TypeOf((*MockMicroURLRepo)(nil).PushEvent), ctx, e)
}

// Save mocks base method.
func (m *MockMicroURLRepo) Save(ctx context.Context, lURL string) (byte, uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, lURL)
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Save indicates an expected call of Save.
func (mr *MockMicroURLRepoMockRecorder) Save(ctx, lURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMicroURLRepo)(nil).Save), ctx, lURL)
}
