// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	config "murl/internal/config"
	domain "murl/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceConfig is a mock of ServiceConfig interface.
type MockServiceConfig struct {
	ctrl     *gomock.Controller
	recorder *MockServiceConfigMockRecorder
	isgomock struct{}
}

// MockServiceConfigMockRecorder is the mock recorder for MockServiceConfig.
type MockServiceConfigMockRecorder struct {
	mock *MockServiceConfig
}

// NewMockServiceConfig creates a new mock instance.
func NewMockServiceConfig(ctrl *gomock.Controller) *MockServiceConfig {
	mock := &MockServiceConfig{ctrl: ctrl}
	mock.recorder = &MockServiceConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceConfig) EXPECT() *MockServiceConfigMockRecorder {
	return m.recorder
}

// KeySession mocks base method.
func (m *MockServiceConfig) KeySession() config.KeySession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeySession")
	ret0, _ := ret[0].(config.KeySession)
	return ret0
}

// KeySession indicates an expected call of KeySession.
func (mr *MockServiceConfigMockRecorder) KeySession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeySession", reflect.TypeOf((*MockServiceConfig)(nil).KeySession))
}

// ShortBaseURL mocks base method.
func (m *MockServiceConfig) ShortBaseURL() config.ShortBaseURL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortBaseURL")
	ret0, _ := ret[0].(config.ShortBaseURL)
	return ret0
}

// ShortBaseURL indicates an expected call of ShortBaseURL.
func (mr *MockServiceConfigMockRecorder) ShortBaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortBaseURL", reflect.TypeOf((*MockServiceConfig)(nil).ShortBaseURL))
}

// MockAuditlogNotifier is a mock of AuditlogNotifier interface.
type MockAuditlogNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockAuditlogNotifierMockRecorder
	isgomock struct{}
}

// MockAuditlogNotifierMockRecorder is the mock recorder for MockAuditlogNotifier.
type MockAuditlogNotifierMockRecorder struct {
	mock *MockAuditlogNotifier
}

// NewMockAuditlogNotifier creates a new mock instance.
func NewMockAuditlogNotifier(ctrl *gomock.Controller) *MockAuditlogNotifier {
	mock := &MockAuditlogNotifier{ctrl: ctrl}
	mock.recorder = &MockAuditlogNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditlogNotifier) EXPECT() *MockAuditlogNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockAuditlogNotifier) Notify(ctx context.Context, n domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockAuditlogNotifierMockRecorder) Notify(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockAuditlogNotifier)(nil).Notify), ctx, n)
}
