// Code generated by "stringer -type=EvType"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EvUnknown-0]
	_ = x[EvAddURL-1]
	_ = x[EvAddURLBySessionID-2]
	_ = x[EvGetURL-3]
	_ = x[EvGetURLBySessionID-4]
	_ = x[EvBatch-5]
	_ = x[EvBatchBySessionID-6]
}

const _EvType_name = "EvUnknownEvAddURLEvAddURLBySessionIDEvGetURLEvGetURLBySessionIDEvBatchEvBatchBySessionID"

var _EvType_index = [...]uint8{0, 9, 17, 36, 44, 63, 70, 88}

func (i EvType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EvType_index)-1 {
		return "EvType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EvType_name[_EvType_index[idx]:_EvType_index[idx+1]]
}
