// Code generated by reset generator. DO NOT EDIT.
package dto

import (
	"github.com/google/uuid"
)

func (s *AddURL) Reset() {
	if s == nil {
		return
	}
	s.OriginalURL = ""
	s.ShortURL = ""
	s.ConflictFlag = false

}

func (s *AddURLBySessionID) Reset() {
	if s == nil {
		return
	}
	if r, ok := any(&s.AddURL).(interface{ Reset() }); ok {
		r.Reset()
	} else {
		s.AddURL = AddURL{}
	}
	if r, ok := any(&s.SessionID).(interface{ Reset() }); ok {
		r.Reset()
	} else {
		s.SessionID = uuid.UUID{}
	}

}

func (s *Batch) Reset() {
	if s == nil {
		return
	}
	s.Batch = s.Batch[:0]

}

func (s *BatchBySessionID) Reset() {
	if s == nil {
		return
	}
	if r, ok := any(&s.SessionID).(interface{ Reset() }); ok {
		r.Reset()
	} else {
		s.SessionID = uuid.UUID{}
	}
	s.Batch = s.Batch[:0]

}

func (s *DeleteURLBySessionID) Reset() {
	if s == nil {
		return
	}
	if r, ok := any(&s.SessionID).(interface{ Reset() }); ok {
		r.Reset()
	} else {
		s.SessionID = uuid.UUID{}
	}
	s.ShortURLs = s.ShortURLs[:0]

}

func (s *GetURL) Reset() {
	if s == nil {
		return
	}
	s.OriginalURL = ""
	s.ShortURL = ""
	s.IsGone = false

}

func (s *GetURLBySessionID) Reset() {
	if s == nil {
		return
	}
	if r, ok := any(&s.SessionID).(interface{ Reset() }); ok {
		r.Reset()
	} else {
		s.SessionID = uuid.UUID{}
	}
	s.Result = s.Result[:0]

}
