// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	event "murl/internal/model/event"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHandlersConfig is a mock of HandlersConfig interface.
type MockHandlersConfig struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersConfigMockRecorder
}

// MockHandlersConfigMockRecorder is the mock recorder for MockHandlersConfig.
type MockHandlersConfigMockRecorder struct {
	mock *MockHandlersConfig
}

// NewMockHandlersConfig creates a new mock instance.
func NewMockHandlersConfig(ctrl *gomock.Controller) *MockHandlersConfig {
	mock := &MockHandlersConfig{ctrl: ctrl}
	mock.recorder = &MockHandlersConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlersConfig) EXPECT() *MockHandlersConfigMockRecorder {
	return m.recorder
}

// MockMicroURLService is a mock of MicroURLService interface.
type MockMicroURLService struct {
	ctrl     *gomock.Controller
	recorder *MockMicroURLServiceMockRecorder
}

// MockMicroURLServiceMockRecorder is the mock recorder for MockMicroURLService.
type MockMicroURLServiceMockRecorder struct {
	mock *MockMicroURLService
}

// NewMockMicroURLService creates a new mock instance.
func NewMockMicroURLService(ctrl *gomock.Controller) *MockMicroURLService {
	mock := &MockMicroURLService{ctrl: ctrl}
	mock.recorder = &MockMicroURLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMicroURLService) EXPECT() *MockMicroURLServiceMockRecorder {
	return m.recorder
}

// AddURL mocks base method.
func (m *MockMicroURLService) AddURL(ctx context.Context, url string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURL", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddURL indicates an expected call of AddURL.
func (mr *MockMicroURLServiceMockRecorder) AddURL(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURL", reflect.TypeOf((*MockMicroURLService)(nil).AddURL), ctx, url)
}

// Batch mocks base method.
func (m *MockMicroURLService) Batch(ctx context.Context, e event.Event) (event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Batch", ctx, e)
	ret0, _ := ret[0].(event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Batch indicates an expected call of Batch.
func (mr *MockMicroURLServiceMockRecorder) Batch(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*MockMicroURLService)(nil).Batch), ctx, e)
}

// GetURL mocks base method.
func (m *MockMicroURLService) GetURL(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockMicroURLServiceMockRecorder) GetURL(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockMicroURLService)(nil).GetURL), ctx, url)
}

// Ping mocks base method.
func (m *MockMicroURLService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMicroURLServiceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMicroURLService)(nil).Ping), ctx)
}
