// Code generated by MockGen. DO NOT EDIT.
// Source: serve.go
//
// Generated by this command:
//
//	mockgen -source=serve.go -destination=serve_mock_test.go -package=handlers
//

// Package handlers is a generated GoMock package.
package handlers

import (
	config "murl/internal/config"
	http "net/http"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRouterConfig is a mock of RouterConfig interface.
type MockRouterConfig struct {
	ctrl     *gomock.Controller
	recorder *MockRouterConfigMockRecorder
	isgomock struct{}
}

// MockRouterConfigMockRecorder is the mock recorder for MockRouterConfig.
type MockRouterConfigMockRecorder struct {
	mock *MockRouterConfig
}

// NewMockRouterConfig creates a new mock instance.
func NewMockRouterConfig(ctrl *gomock.Controller) *MockRouterConfig {
	mock := &MockRouterConfig{ctrl: ctrl}
	mock.recorder = &MockRouterConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouterConfig) EXPECT() *MockRouterConfigMockRecorder {
	return m.recorder
}

// CompressibleContentTypes mocks base method.
func (m *MockRouterConfig) CompressibleContentTypes() map[string]struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressibleContentTypes")
	ret0, _ := ret[0].(map[string]struct{})
	return ret0
}

// CompressibleContentTypes indicates an expected call of CompressibleContentTypes.
func (mr *MockRouterConfigMockRecorder) CompressibleContentTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressibleContentTypes", reflect.TypeOf((*MockRouterConfig)(nil).CompressibleContentTypes))
}

// JWTSecretKey mocks base method.
func (m *MockRouterConfig) JWTSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JWTSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// JWTSecretKey indicates an expected call of JWTSecretKey.
func (mr *MockRouterConfigMockRecorder) JWTSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWTSecretKey", reflect.TypeOf((*MockRouterConfig)(nil).JWTSecretKey))
}

// JWTTTL mocks base method.
func (m *MockRouterConfig) JWTTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JWTTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// JWTTTL indicates an expected call of JWTTTL.
func (mr *MockRouterConfigMockRecorder) JWTTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWTTTL", reflect.TypeOf((*MockRouterConfig)(nil).JWTTTL))
}

// KeySession mocks base method.
func (m *MockRouterConfig) KeySession() config.KeySession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeySession")
	ret0, _ := ret[0].(config.KeySession)
	return ret0
}

// KeySession indicates an expected call of KeySession.
func (mr *MockRouterConfigMockRecorder) KeySession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeySession", reflect.TypeOf((*MockRouterConfig)(nil).KeySession))
}

// MaxBodySize mocks base method.
func (m *MockRouterConfig) MaxBodySize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxBodySize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// MaxBodySize indicates an expected call of MaxBodySize.
func (mr *MockRouterConfigMockRecorder) MaxBodySize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxBodySize", reflect.TypeOf((*MockRouterConfig)(nil).MaxBodySize))
}

// RouterType mocks base method.
func (m *MockRouterConfig) RouterType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouterType")
	ret0, _ := ret[0].(string)
	return ret0
}

// RouterType indicates an expected call of RouterType.
func (mr *MockRouterConfigMockRecorder) RouterType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouterType", reflect.TypeOf((*MockRouterConfig)(nil).RouterType))
}

// MockIServeConfig is a mock of IServeConfig interface.
type MockIServeConfig struct {
	ctrl     *gomock.Controller
	recorder *MockIServeConfigMockRecorder
	isgomock struct{}
}

// MockIServeConfigMockRecorder is the mock recorder for MockIServeConfig.
type MockIServeConfigMockRecorder struct {
	mock *MockIServeConfig
}

// NewMockIServeConfig creates a new mock instance.
func NewMockIServeConfig(ctrl *gomock.Controller) *MockIServeConfig {
	mock := &MockIServeConfig{ctrl: ctrl}
	mock.recorder = &MockIServeConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServeConfig) EXPECT() *MockIServeConfigMockRecorder {
	return m.recorder
}

// CertFile mocks base method.
func (m *MockIServeConfig) CertFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CertFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// CertFile indicates an expected call of CertFile.
func (mr *MockIServeConfigMockRecorder) CertFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CertFile", reflect.TypeOf((*MockIServeConfig)(nil).CertFile))
}

// EnabledHTTPS mocks base method.
func (m *MockIServeConfig) EnabledHTTPS() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnabledHTTPS")
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnabledHTTPS indicates an expected call of EnabledHTTPS.
func (mr *MockIServeConfigMockRecorder) EnabledHTTPS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnabledHTTPS", reflect.TypeOf((*MockIServeConfig)(nil).EnabledHTTPS))
}

// KeyFile mocks base method.
func (m *MockIServeConfig) KeyFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// KeyFile indicates an expected call of KeyFile.
func (mr *MockIServeConfigMockRecorder) KeyFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyFile", reflect.TypeOf((*MockIServeConfig)(nil).KeyFile))
}

// ListenAddr mocks base method.
func (m *MockIServeConfig) ListenAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// ListenAddr indicates an expected call of ListenAddr.
func (mr *MockIServeConfigMockRecorder) ListenAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAddr", reflect.TypeOf((*MockIServeConfig)(nil).ListenAddr))
}

// MockMicroURLHandlers is a mock of MicroURLHandlers interface.
type MockMicroURLHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockMicroURLHandlersMockRecorder
	isgomock struct{}
}

// MockMicroURLHandlersMockRecorder is the mock recorder for MockMicroURLHandlers.
type MockMicroURLHandlersMockRecorder struct {
	mock *MockMicroURLHandlers
}

// NewMockMicroURLHandlers creates a new mock instance.
func NewMockMicroURLHandlers(ctrl *gomock.Controller) *MockMicroURLHandlers {
	mock := &MockMicroURLHandlers{ctrl: ctrl}
	mock.recorder = &MockMicroURLHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMicroURLHandlers) EXPECT() *MockMicroURLHandlersMockRecorder {
	return m.recorder
}

// APIShorten mocks base method.
func (m *MockMicroURLHandlers) APIShorten() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIShorten")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// APIShorten indicates an expected call of APIShorten.
func (mr *MockMicroURLHandlersMockRecorder) APIShorten() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIShorten", reflect.TypeOf((*MockMicroURLHandlers)(nil).APIShorten))
}

// APIShortenBatch mocks base method.
func (m *MockMicroURLHandlers) APIShortenBatch() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIShortenBatch")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// APIShortenBatch indicates an expected call of APIShortenBatch.
func (mr *MockMicroURLHandlersMockRecorder) APIShortenBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIShortenBatch", reflect.TypeOf((*MockMicroURLHandlers)(nil).APIShortenBatch))
}

// APIUserURLs mocks base method.
func (m *MockMicroURLHandlers) APIUserURLs() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIUserURLs")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// APIUserURLs indicates an expected call of APIUserURLs.
func (mr *MockMicroURLHandlersMockRecorder) APIUserURLs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIUserURLs", reflect.TypeOf((*MockMicroURLHandlers)(nil).APIUserURLs))
}

// AddURL mocks base method.
func (m *MockMicroURLHandlers) AddURL() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURL")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// AddURL indicates an expected call of AddURL.
func (mr *MockMicroURLHandlersMockRecorder) AddURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURL", reflect.TypeOf((*MockMicroURLHandlers)(nil).AddURL))
}

// Default mocks base method.
func (m *MockMicroURLHandlers) Default() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Default")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Default indicates an expected call of Default.
func (mr *MockMicroURLHandlersMockRecorder) Default() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Default", reflect.TypeOf((*MockMicroURLHandlers)(nil).Default))
}

// DeleteAPIUserURLs mocks base method.
func (m *MockMicroURLHandlers) DeleteAPIUserURLs() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAPIUserURLs")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// DeleteAPIUserURLs indicates an expected call of DeleteAPIUserURLs.
func (mr *MockMicroURLHandlersMockRecorder) DeleteAPIUserURLs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIUserURLs", reflect.TypeOf((*MockMicroURLHandlers)(nil).DeleteAPIUserURLs))
}

// GetURL mocks base method.
func (m *MockMicroURLHandlers) GetURL() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// GetURL indicates an expected call of GetURL.
func (mr *MockMicroURLHandlersMockRecorder) GetURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockMicroURLHandlers)(nil).GetURL))
}

// Ping mocks base method.
func (m *MockMicroURLHandlers) Ping() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMicroURLHandlersMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMicroURLHandlers)(nil).Ping))
}
